service: import-service

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  environment:
    BUCKET_NAME: bucket-for-products
    MY_AWS_REGION: ${opt:region, 'eu-central-1'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:ListBucket
        - s3:DeleteObject
      Resource:
        - arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/*
        - arn:aws:s3:::${self:provider.environment.BUCKET_NAME}

functions:
  importProductsFile:
    handler: handlers/importProductsFile.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors:
            origins:
              - "*"
            headers:
              - Content-Type
            allowCredentials: false
      - http:
          path: import
          method: options
          cors:
            origins:
              - "*"
            headers:
              - Content-Type
            allowCredentials: false

  importFileParser:
    handler: handlers/importFileParser.importFileParser
    events:
      - s3:
          bucket: ${self:provider.environment.BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
            - suffix: .csv

package:
  exclude:
    - node_modules/**
    - "!node_modules/csv-parser/**"
    - "!node_modules/@aws-sdk/**"
    - "!node_modules/@types/**"
